  - name: Ensure old versions are not installed            
    package:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: Install required packages
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-pip
      state: present
      update_cache: yes
  
  - name: Get dpkg architecture
    shell: dpkg --print-architecture
    register: dpkg_arch
  
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb [arch={{dpkg_arch.stdout}} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ansible_facts.distribution_release}} stable
      filename: docker
      state: present

  - name: Install docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes
      